# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hongwei Chu's Github Pages
email: hongweichu.ouc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    It is no use doing what you like, you have got to like what you do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willseeyou.github.io" # the base hostname & protocol for your site
github_username: willseeyou

# Build settings
markdown: kramdown
# markdown: redcarpet
